const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        light: {
          whiteBackground: "#FFFFFF",
          primaryBackground: "#FFFCFA",
          stroke: "#E5E5E5",
          theme: "#ff9966",
          primaryText: "#333333",
          secondaryText: "#999999",
          orange: "#FF9966",
          lightOrange: "#fff4f4",
          grey: "#fff7f0",
          status: {
            vouching: "#BE75FF",
            registered: "#00D9A1",
            removed: "#F60C6E",
            revocation: "#FF9966",
            claim: "#00D1FF",
            challenged: "#FFBE66",
            withdrawn: "#999999",
            expired: "#333333",
            transferred: "#3F6212",
            transferring: "#ba7264",
            rejected: "#D90429",
          },
          purple: "#BE75FF",
        },
        dark: {
          whiteBackground: "#292D35",
          primaryBackground: "#1E2129",
          stroke: "#3A3E48",
          theme: "#FF8A66",
          primaryText: "#F7F3EF",
          secondaryText: "#B8B1C2",
          orange: "#FF8A66",
          lightOrange: "#2F333D",
          grey: "#2F333D",
          status: {
            vouching: "#D09BFF",
            registered: "#79FFDC",
            removed: "#FF8A66",
            revocation: "#FF8A66",
            claim: "#8CEAFF",
            challenged: "#FFE16B",
            withdrawn: "#F7F3EF",
            expired: "#F7F3EF",
            transferred: "#9BD157",
            transferring: "#A6816E",
            rejected: "#F60C6E",
          },
          purple: "#D09BFF",
        },
        peach: "#FFB08A",
      },
      borderRadius: {
        card: "26px",
        input: "16px",
        btn: "16px",
      },
      boxShadow: {
        soft: "0 20px 50px rgba(0,0,0,0.28)",
        "soft-inset":
          "0 20px 50px rgba(0,0,0,0.28), inset 0 1px 0 rgba(255,255,255,0.045)",
      },
      transitionTimingFunction: {
        premium: "cubic-bezier(0.22, 0.61, 0.36, 1)",
      },
      animation: {
        flip: "flip 5s linear infinite",
        fadeOut: "fadeOut 0.4s ease-out forwards",
        fadeIn: "fadeIn 0.3s ease-out forwards",
        accordionItemIn:
          "accordionItemIn 0.6s cubic-bezier(0.22, 0.61, 0.36, 1) both",
        mediaResolve:
          "mediaResolve 0.6s cubic-bezier(0.22, 0.61, 0.36, 1) both",
      },
      keyframes: {
        flip: {
          "0%, 100%": { transform: "rotateY(0deg)" },
          "50%": { transform: "rotateY(360deg)" },
        },
        fadeOut: {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        accordionItemIn: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        mediaResolve: {
          "0%": {
            opacity: "0",
            filter: "blur(12px)",
            transform: "scale(1.02)",
          },
          "100%": { opacity: "1", filter: "blur(0)", transform: "scale(1)" },
        },
        // progress: {
        //   "0%": { transform: "scaleX(1)" },
        //   "100%": { transform: "scaleX(0)" },
        // },
      },
      fontFamily: {
        sans: ["Inter", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
  safelist: [
    "bg-status-vouching",
    "bg-status-registered",
    "bg-status-removed",
    "bg-status-revocation",
    "bg-status-claim",
    "bg-status-challenged",
    "bg-status-withdrawn",
    "bg-status-expired",
    "bg-status-transferred",
    "bg-status-transferring",
    "text-status-vouching",
    "text-status-registered",
    "text-status-removed",
    "text-status-revocation",
    "text-status-claim",
    "text-status-challenged",
    "text-status-withdrawn",
    "text-status-expired",
    "text-status-transferred",
    "text-status-transferring",
    "border-status-vouching",
    "border-status-registered",
    "border-status-removed",
    "border-status-revocation",
    "border-status-claim",
    "border-status-challenged",
    "border-status-withdrawn",
    "border-status-expired",
    "border-status-transferred",
    "border-status-transferring",
    "bg-status-rejected",
    "text-status-rejected",
    "border-status-rejected",
    "text-purple",
    "text-status-vouching",
    "border-status-vouching",
  ],
};
