query PohReferralDashboard($pagination: PaginationArgs) {
  humanityFlag
  pohReferrals(pagination: $pagination) {
    count
    hasNextPage
    items {
      item {
        refereeHumanityId
        reviewStatus
        rewardAmount
        payoutTransaction {
          status
          txHash
        }
        refereeFlag {
          isFlagged
        }
      }
    }
  }
}
