query HumanityEvents($humanityId: Bytes!) {
  humanityEvents(
    where: { humanityId: $humanityId }
    orderBy: timestamp
    orderDirection: asc
  ) {
    id
    timestamp
    type
    requestIndex
    transferHash
    disputeId
    appealRound
    revocation
  }
}
