query HumanityIdByClaimer($address: String!, $now: BigInt!) {
  registrations(
    where: { claimer: $address, expirationTime_gt: $now }
    first: 1
  ) {
    humanity {
      id
    }
  }
  crossChainRegistrations(
    where: { claimer: $address, expirationTime_gt: $now }
    first: 1
  ) {
    id
  }
}


