query Me($id: ID!) {
  claimer(id: $id) {
    registration {
      id
      expirationTime
    }
    currentRequest {
      index
      status {
        id
      }
      humanity {
        id
      }
    }
  }
}
