query Request($id: ID!, $humanityId: Bytes!) {
  request(id: $id) {
    id
    status {
      id
    }
    winnerParty {
      id
    }
    index
    expirationTime
    revocation
    registrationEvidenceRevokedReq
    requester
    creationTime
    lastStatusChange
    inTransferHash
    punishedVouchSourceRequest {
      humanity {
        id
      }
      index
    }
    punishedVouchReason {
      id
    }
    punishedVouchTimestamp
    vouches {
      voucher {
        id
      }
    }
    humanity {
      id
      nbRequests
      nbPendingRequests
      nbLegacyRequests
      registration {
        expirationTime
        claimer {
          id
        }
      }
      ...winnerClaim
    }
    claimer {
      id
      name
      vouchesReceived(where: { humanity_: { id: $humanityId } }) {
        from {
          id
          registration {
            expirationTime
            humanity {
              vouching
            }
          }
        }
        humanity {
          id
        }
      }
      vouches {
        for {
          id
          name
        }
      }
    }
    evidenceGroup {
      evidence(orderBy: creationTime, orderDirection: desc) {
        id
        uri
        creationTime
        submitter
      }
    }
    challenges(orderBy: creationTime) {
      id
      creationTime
      reason {
        id
      }
      disputeId
      challenger {
        id
      }
      nbRounds
      rounds(orderBy: index) {
        creationTime
        index
        requesterFund {
          amount
        }
        challengerFund {
          amount
        }
      }
    }
    arbitratorHistory {
      updateTime
      registrationMeta
      id
      arbitrator
      extraData
    }
  }
}
